const mongoose = require("mongoose");
const Product = require("./models/product.model");

const products = [
  {
    img: "/products/Shirts/1.1.jpg",
    name: "Infinite Imagination",
    price: "12.99",
    salePrice: "",
    quantity: "10",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Shirts/1.jpg",
    name: "Lyrical Mastermind",
    price: "19.95",
    salePrice: "",
    quantity: "10",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Shirts/2.1.jpg",
    name: "Bold and Beautiful",
    price: "8.50",
    salePrice: "",
    quantity: "10",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Shirts/2.jpg",
    name: "Wanderlust Warrior",
    price: "14.75",
    salePrice: "",
    quantity: "10",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Shirts/3.jpg",
    name: "Stay Curious",
    price: "21.99",
    salePrice: "",
    quantity: "10",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Shirts/4.jpg",
    name: "Rebel with a Cause",
    price: "10.25",
    salePrice: "",
    quantity: "10",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Shirts/5.jpg",
    name: "Radiate Positivity",
    price: "16.50",
    salePrice: "",
    quantity: "10",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Shirts/6.jpg",
    name: "Elevate and Inspire",
    price: "13.45",
    salePrice: "",
    quantity: "10",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Shirts/7.jpg",
    name: "Fearless Explorer",
    price: "18.75",
    salePrice: "",
    quantity: "10",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Shirts/7.1.jpg",
    name: "Unleash Your Potential",
    price: "9.99",
    salePrice: "",
    quantity: "10",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Shirts/8.jpg",
    name: "Live, Laugh, Love",
    price: "22.50",
    salePrice: "",
    quantity: "10",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Shirts/10.jpg",
    name: "Be Kind, Be Brave",
    price: "11.95",
    salePrice: "",
    quantity: "10",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Shirts/11.jpg",
    name: "Embrace the Chaos",
    price: "17.25",
    salePrice: "",
    quantity: "10",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Shirts/12.jpg",
    name: "Vibes Only",
    price: "15.50",
    salePrice: "",
    quantity: "10",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Shirts/13.jpg",
    name: "Peaceful Warrior",
    price: "20.99",
    salePrice: "",
    quantity: "10",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Shirts/14.jpg",
    name: "Sunshine State of Mind",
    price: "7.95",
    salePrice: "",
    quantity: "10",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Shirts/15.jpg",
    name: "Wild and Free",
    price: "9.75",
    salePrice: "",
    quantity: "10",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Shirts/16.jpg",
    name: "Adventure Awaits",
    price: "14.99",
    salePrice: "",
    quantity: "10",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Shirts/17.jpg",
    name: "Find Your Passion",
    price: "22.50",
    salePrice: "",
    quantity: "10",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Shirts/18.jpg",
    name: "Empowered by Equality",
    price: "23.75",
    salePrice: "",
    quantity: "10",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Shirts/19.jpg",
    name: "Nature's Canvas",
    price: "18.99",
    salePrice: "",
    quantity: "10",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Shirts/20.jpg",
    name: "Mind Over Matter",
    price: "7.95",
    salePrice: "",
    quantity: "10",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Shirts/21.jpg",
    name: "Inspire and be Inspired",
    price: "8.50",
    salePrice: "",
    quantity: "10",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Shirts/22.jpg",
    name: "Artistic Expression",
    price: "10.25",
    salePrice: "",
    quantity: "10",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Shirts/23.jpg",
    name: "Free Spirit",
    price: "20.50",
    salePrice: "",
    quantity: "10",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Shirts/24.jpg",
    name: "Strength in Unity",
    price: "15.25",
    salePrice: "",
    quantity: "10",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Shirts/25.jpg",
    name: "Dare to Dream",
    price: "11.50",
    salePrice: "",
    quantity: "10",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Shirts/26.jpg",
    name: "Positive Vibes Only",
    price: "17.50",
    salePrice: "",
    quantity: "10",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Shirts/27.jpg",
    name: "Spread Love, Not Hate",
    price: "12.99",
    salePrice: "",
    quantity: "10",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Shirts/28.jpg",
    name: "Unleash Your Inner Warrior",
    price: "15.99",
    salePrice: "",
    quantity: "10",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Shirts/29.jpg",
    name: "Stay Weird, Stay Wonderful",
    price: "19.50",
    salePrice: "",
    quantity: "10",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Shirts/30.jpg",
    name: "Make Waves",
    price: "13.25",
    salePrice: "",
    quantity: "10",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Shirts/31.jpg",
    name: "Keep Calm and Carry On",
    price: "16.50",
    salePrice: "",
    quantity: "10",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Shirts/32.jpg",
    name: "Choose Joy",
    price: "18.25",
    salePrice: "",
    quantity: "10",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Shirts/33.jpg",
    name: "DynamicDesigns",
    price: "12.99",
    salePrice: "",
    quantity: "10",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Shirts/34.jpg",
    name: "TimelessTrends",
    price: "17.99",
    salePrice: "",
    quantity: "10",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Shirts/35.jpg",
    name: "FashionForward",
    price: "7.50",
    salePrice: "",
    quantity: "10",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Shirts/36.jpg",
    name: "ChicContours",
    price: "10.50",
    salePrice: "",
    quantity: "10",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/shoes/1.jpg",
    name: "SoleStride",
    price: "89.99",
    salePrice: "",
    quantity: "23",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/shoes/2.jpg",
    name: "AirFlex",
    price: "124.50",
    salePrice: "",
    quantity: "23",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/shoes/3.jpg",
    name: "SwiftStep",
    price: "79.95",
    salePrice: "",
    quantity: "23",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/shoes/4.jpg",
    name: "UrbanKicks",
    price: "149.99",
    salePrice: "",
    quantity: "23",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/shoes/5.jpg",
    name: "GlideTech",
    price: "109.75",
    salePrice: "",
    quantity: "23",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/shoes/6.jpg",
    name: "SprintFusion",
    price: "139.50",
    salePrice: "",
    quantity: "23",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/shoes/7.jpg",
    name: "StealthStride",
    price: "94.25",
    salePrice: "",
    quantity: "23",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/shoes/8.jpg",
    name: "VelocityVenture",
    price: "169.99",
    salePrice: "",
    quantity: "23",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/shoes/9.jpg",
    name: "RetroRevive",
    price: "119.50",
    salePrice: "",
    quantity: "23",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/shoes/10.jpg",
    name: "DynamicDasher",
    price: "99.95",
    salePrice: "",
    quantity: "23",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/shoes/11.jpg",
    name: "StrideX",
    price: "134.99",
    salePrice: "",
    quantity: "23",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/shoes/12.jpg",
    name: "GravityGrip",
    price: "89.50",
    salePrice: "",
    quantity: "23",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/shoes/13.jpg",
    name: "PowerPulse",
    price: "154.75",
    salePrice: "",
    quantity: "23",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Bags/1.png",
    name: "TrendyTote",
    price: "49.99",
    salePrice: "",
    quantity: "15",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Bags/2.png",
    name: "UrbanCarry",
    price: "79.50",
    salePrice: "",
    quantity: "15",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Bags/3.png",
    name: "ChicSatchel",
    price: "39.95",
    salePrice: "",
    quantity: "15",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Bags/4.png",
    name: "StylishSling",
    price: "69.75",
    salePrice: "",
    quantity: "15",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Hoodies/1.jpg",
    name: "CozyComfort",
    price: "39.99",
    salePrice: "",
    quantity: "18",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Hoodies/2.jpg",
    name: "UrbanHood",
    price: "49.50",
    salePrice: "",
    quantity: "18",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Hoodies/3.jpg",
    name: "StreetStyle",
    price: "34.95",
    salePrice: "",
    quantity: "18",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Hoodies/4.jpg",
    name: "ChillVibes",
    price: "59.99",
    salePrice: "",
    quantity: "18",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Hoodies/5.jpg",
    name: "HoodedHaven",
    price: "44.75",
    salePrice: "",
    quantity: "18",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Hoodies/6.jpg",
    name: "CasualCocoon",
    price: "54.50",
    salePrice: "",
    quantity: "18",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Hoodies/7.jpg",
    name: "CosmicCozy",
    price: "37.25",
    salePrice: "",
    quantity: "18",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Hoodies/8.jpg",
    name: "FleeceFusion",
    price: "69.99",
    salePrice: "",
    quantity: "18",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Hoodies/9.jpg",
    name: "SnugStreet",
    price: "49.50",
    salePrice: "",
    quantity: "18",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Hoodies/10.jpg",
    name: "HoodedHaven",
    price: "36.95",
    salePrice: "",
    quantity: "18",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Hoodies/11.jpg",
    name: "RelaxedRevolution",
    price: "64.99",
    salePrice: "",
    quantity: "18",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Hoodies/12.jpg",
    name: "HoodedHustle",
    price: "47.50",
    salePrice: "",
    quantity: "18",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Hoodies/13.jpg",
    name: "LaidbackLuxury",
    price: "74.75",
    salePrice: "",
    quantity: "18",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Hoodies/14.jpg",
    name: "TrendyThreads",
    price: "54.99",
    salePrice: "",
    quantity: "18",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Hoodies/15.jpg",
    name: "HoodieHaven",
    price: "62.25",
    salePrice: "",
    quantity: "18",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Hoodies/16.jpg",
    name: "UrbanUtopia",
    price: "69.99",
    salePrice: "",
    quantity: "18",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Hoodies/17.jpg",
    name: "HoodedHarmony",
    price: "44.75",
    salePrice: "",
    quantity: "18",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Pants/1.png",
    name: "StyleSavvy",
    price: "79.95",
    salePrice: "",
    quantity: "18",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Pants/2.1.png",
    name: "UrbanChic",
    price: "34.50",
    salePrice: "",
    quantity: "18",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Pants/2.jpg",
    name: "Trendsetters",
    price: "79.95",
    salePrice: "",
    quantity: "18",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Pants/3.1.jpg",
    name: "FashionFlex",
    price: "59.99",
    salePrice: "",
    quantity: "18",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Pants/3.jpg",
    name: "StreetCouture",
    price: "44.75",
    salePrice: "",
    quantity: "18",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Pants/4.1.png",
    name: "ElevatedEssentials",
    price: "69.50",
    salePrice: "",
    quantity: "18",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Pants/4.jpg",
    name: "SleekSilhouettes",
    price: "54.25",
    salePrice: "",
    quantity: "18",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Pants/5.jpg",
    name: "DynamicDenim",
    price: "89.99",
    salePrice: "",
    quantity: "18",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Pants/6.jpg",
    name: "ModishMotion",
    price: "64.50",
    salePrice: "",
    quantity: "18",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Pants/7.1.png",
    name: "VersaPants",
    price: "39.95",
    salePrice: "",
    quantity: "18",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Pants/7.jpg",
    name: "ChicComfort",
    price: "49.50",
    salePrice: "",
    quantity: "18",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Pants/8.1.png",
    name: "ContemporaryClass",
    price: "94.75",
    salePrice: "",
    quantity: "18",
    dis: "",
    isAvailable: true,
  },
  {
    img: "/products/Pants/8.png",
    name: "EffortlessElegance",
    price: "84.25",
    salePrice: "",
    quantity: "18",
    dis: "",
    isAvailable: true,
  },
];

mongoose
  .connect(process.env.MONGO_URI)
  .then(() => {
    console.log("Mongo Connection Open");
  })
  .catch((err) => console.log(err));

const productSeed = async () => {
  const addedProduct = await Product.insertMany(products);

  if (addedProduct) {
    console.log("Products Added");
  }
};

productSeed().then(() => {
  mongoose.connection.close();
});
